name: Checkov Github action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [main]

jobs:
  checkov-job:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Prisma Cloud
    env:
      PRISMA_API_URL: https://api.eu.prismacloud.io/
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Prisma Cloud action
        id: Checkov
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: ${{ secrets.PRISMA_API_URL }}
        with:
          directory: '.'
          api-key: ${{ secrets.PRISMA_ACCESS_KEY }}::${{ secrets.PRISMA_SECRET_KEY }}
          output_format: cli
          soft_fail: true
          quiet: true
          framework: sca_package

      - name: Expose report
        uses: actions/upload-artifact@v3
        with:
          name: SARIF results
          path: results.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
